version: "3.7"

services:
  kajappka-verifier-mock:
    build:
      context: verifier-mock
      dockerfile: docker/production/Dockerfile

  kajappka-rating-service:
    build:
      context: rating-service
      dockerfile: docker/production/Dockerfile
